name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: LabaApteka

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: LabaApteka/dist/windows